/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.NewGUI.Panels.AddOrder.AddItem.ClothingPanel;

import com.bookstore.NewGUI.ComboBoxHelper.ComboBoxRenderer;
import com.bookstore.NewGUI.Panels.AddOrder.AddItem.ClothingPanel.*;
import java.awt.Color;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;

/**
 *
 * @author aaron
 */
public class ClothingPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewBookPanel
     */
    public ClothingPanel() {
        initComponents();
        setScrollPaneHighlights();
    }
    
    private void setScrollPaneHighlights() {
        SizesField.setSelectionBackground(new Color(71,1,194));
        ColorsField.setSelectionBackground(new Color(71,1,194));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NamePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        PricePanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PriceField = new javax.swing.JTextField();
        SizesPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SizesField = new javax.swing.JList<>();
        ColorsPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ColorsField = new javax.swing.JList<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));

        setBackground(new java.awt.Color(33, 33, 33));
        setMinimumSize(new java.awt.Dimension(850, 255));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(850, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        NamePanel.setBackground(new java.awt.Color(33, 33, 33));
        NamePanel.setPreferredSize(new java.awt.Dimension(750, 40));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5);
        flowLayout1.setAlignOnBaseline(true);
        NamePanel.setLayout(flowLayout1);

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));
        jPanel2.setPreferredSize(new java.awt.Dimension(340, 100));
        java.awt.FlowLayout flowLayout5 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout5.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout5);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");
        jPanel2.add(jLabel1);

        NameField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NameField.setToolTipText("Enter Book Name");
        NameField.setMinimumSize(new java.awt.Dimension(200, 28));
        NameField.setPreferredSize(new java.awt.Dimension(200, 28));
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(NameField);

        NamePanel.add(jPanel2);

        add(NamePanel);

        PricePanel.setBackground(new java.awt.Color(33, 33, 33));
        PricePanel.setPreferredSize(new java.awt.Dimension(750, 40));
        java.awt.FlowLayout flowLayout7 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5);
        flowLayout7.setAlignOnBaseline(true);
        PricePanel.setLayout(flowLayout7);

        jPanel4.setBackground(new java.awt.Color(33, 33, 33));
        jPanel4.setPreferredSize(new java.awt.Dimension(340, 100));
        java.awt.FlowLayout flowLayout6 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout6.setAlignOnBaseline(true);
        jPanel4.setLayout(flowLayout6);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Price:");
        jPanel4.add(jLabel2);

        PriceField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PriceField.setToolTipText("Enter Book Name");
        PriceField.setMinimumSize(new java.awt.Dimension(200, 28));
        PriceField.setPreferredSize(new java.awt.Dimension(200, 28));
        PriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceFieldActionPerformed(evt);
            }
        });
        jPanel4.add(PriceField);

        PricePanel.add(jPanel4);

        add(PricePanel);

        SizesPanel.setBackground(new java.awt.Color(33, 33, 33));
        SizesPanel.setMinimumSize(new java.awt.Dimension(154, 80));
        SizesPanel.setPreferredSize(new java.awt.Dimension(750, 80));
        java.awt.FlowLayout flowLayout9 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5);
        flowLayout9.setAlignOnBaseline(true);
        SizesPanel.setLayout(flowLayout9);

        jPanel6.setBackground(new java.awt.Color(33, 33, 33));
        jPanel6.setMinimumSize(new java.awt.Dimension(114, 120));
        jPanel6.setName(""); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(340, 120));
        java.awt.FlowLayout flowLayout8 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout8.setAlignOnBaseline(true);
        jPanel6.setLayout(flowLayout8);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sizes:");
        jPanel6.add(jLabel3);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 100));

        SizesField.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "XXS", "XS", "S", "M", "L", "XL", "XXL", "XXXL" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        SizesField.setToolTipText("");
        jScrollPane1.setViewportView(SizesField);

        jPanel6.add(jScrollPane1);

        SizesPanel.add(jPanel6);

        add(SizesPanel);

        ColorsPanel.setBackground(new java.awt.Color(33, 33, 33));
        ColorsPanel.setMinimumSize(new java.awt.Dimension(164, 80));
        ColorsPanel.setName(""); // NOI18N
        ColorsPanel.setPreferredSize(new java.awt.Dimension(750, 80));
        java.awt.FlowLayout flowLayout11 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5);
        flowLayout11.setAlignOnBaseline(true);
        ColorsPanel.setLayout(flowLayout11);

        jPanel8.setBackground(new java.awt.Color(33, 33, 33));
        jPanel8.setMinimumSize(new java.awt.Dimension(124, 120));
        jPanel8.setPreferredSize(new java.awt.Dimension(340, 120));
        jPanel8.setRequestFocusEnabled(false);
        java.awt.FlowLayout flowLayout10 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout10.setAlignOnBaseline(true);
        jPanel8.setLayout(flowLayout10);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Colors:");
        jPanel8.add(jLabel4);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 100));

        ColorsField.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "RED", "ORANGE", "YELLOW", "GREEN", "BLUE", "PURPLE", "RED", "BLACK", "GREY", "WHITE" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ColorsField);

        jPanel8.add(jScrollPane2);

        ColorsPanel.add(jPanel8);

        add(ColorsPanel);
        add(filler1);
    }// </editor-fold>//GEN-END:initComponents

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void PriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<String> ColorsField;
    private javax.swing.JPanel ColorsPanel;
    public javax.swing.JTextField NameField;
    private javax.swing.JPanel NamePanel;
    public javax.swing.JTextField PriceField;
    private javax.swing.JPanel PricePanel;
    public javax.swing.JList<String> SizesField;
    private javax.swing.JPanel SizesPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
