/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.NewGUI.Panels.Shifts;

import com.bookstore.NewGUI.Panels.WeeklyOrders.*;
import com.bookstore.DataManager.AccountManager;
import com.bookstore.DataManager.WeeklyOrdersManager;
import com.bookstore.Helpers.CalendarHelper;
import com.bookstore.Models.Account;
import com.bookstore.Models.Item;
import com.bookstore.Models.Order;
import com.bookstore.Models.WeeklyOrder;
import com.bookstore.NewGUI.ButtonHelper.ButtonHelper;
import com.bookstore.NewGUI.MainDisplay;
import com.bookstore.NewGUI.Panels.AddOrder.AddOrderPanel;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author aaron
 */
public class ChangeAvailabilityPanel extends javax.swing.JPanel {
    

    private String[] getColumnNames() {
                //                            (Account)
        // sendDate, AccountID, OrderID, FirstName, LastName, items list as string
        String[] columnNames = {
            "Day of Week",
            "Start Time",
            "End Time"
        };
        return columnNames;
    }

    private Object[][] getData() {
        
        //                            (Account)
        // sendDate, AccountID, OrderID, FirstName, LastName, items list as string
        Object[][] dataArr = new Object[][]{
            {"Mon Nov 28", "09:00:00 EST", "17:00:00 EST"},
            {"Tue Nov 29", "10:00:00 EST", "18:00:00 EST"},
            {"Wed Nov 30", "08:30:00 EST", "16:30:00 EST"},
            {"Thur Dec 1", "08:30:00 EST", "16:30:00 EST"},
            {"Fri Dec 2", "08:30:00 EST", "16:30:00 EST"}
        };
        
        totalHours = 40.0;

        return dataArr;
    }
    
    private void setEnabledDeleteButton(boolean state) {
        jButton4.setEnabled(state);
    }
    
    private void addTableSelectionListener() {
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    //System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
                    setEnabledDeleteButton(true);
                }
            }
        });
    }
    
    private void sortTableRows() {
        jTable1.setAutoCreateRowSorter(true);
        List<RowSorter.SortKey> sortKeys = new ArrayList<>(1);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
        jTable1.getRowSorter().setSortKeys(sortKeys);
    }
    
    /**
     * Creates new form WeeklyOrdersPanelV2
     */
    public ChangeAvailabilityPanel(MainDisplay display) {
        this.display = display;
        initComponents();
        this.buttons = new JButton[]{jButton1, jButton4};
        ButtonHelper.addButtonHighlights(buttons);
        setEnabledDeleteButton(false);
        addTableSelectionListener();
        sortTableRows();
        String weekHoursText = totalHours.toString();
        totalWeekHours.setText(weekHoursText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalWeekHours = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 33, 33));
        setForeground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(850, 500));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(33, 33, 33));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 410));
        jScrollPane1.setRowHeaderView(null);
        jScrollPane1.setViewportView(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(getData(), getColumnNames()));
        jTable1.setSelectionBackground(new java.awt.Color(71, 1, 194));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 110));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 110));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 110));

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));
        jPanel2.setMinimumSize(new java.awt.Dimension(850, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 50));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Hours:");
        jPanel2.add(jLabel2);

        totalWeekHours.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalWeekHours.setForeground(new java.awt.Color(255, 255, 255));
        totalWeekHours.setText("0");
        jPanel2.add(totalWeekHours);

        jPanel1.add(jPanel2);

        jButton1.setText("Add Availability Rule");
        jButton1.setPreferredSize(new java.awt.Dimension(200, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton4.setText("Delete Availability Rule");
        jButton4.setPreferredSize(new java.awt.Dimension(200, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.display.setNewPanel(new AddOrderPanel());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel totalWeekHours;
    // End of variables declaration//GEN-END:variables

    private JButton[] buttons;
    private WeeklyOrder[] data;
    private MainDisplay display;
    private Double totalHours;
    
}
