/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.NewGUI.Panels.Shifts;

import com.bookstore.NewGUI.Panels.WeeklyOrders.*;
import com.bookstore.DataManager.AccountManager;
import com.bookstore.DataManager.WeeklyOrdersManager;
import com.bookstore.Helpers.CalendarHelper;
import com.bookstore.Models.Account;
import com.bookstore.Models.Item;
import com.bookstore.Models.Order;
import com.bookstore.Models.WeeklyOrder;
import com.bookstore.NewGUI.ButtonHelper.ButtonHelper;
import com.bookstore.NewGUI.MainDisplay;
import com.bookstore.NewGUI.Panels.AddOrder.AddOrderPanel;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author aaron
 */
public class ViewDaySchedule extends javax.swing.JPanel {
    
    private WeeklyOrder getWeeklyData() {
        return WeeklyOrdersManager.getWeeklyOrder(CalendarHelper.getFirstDayOfWeek());
    }

    private String[] getColumnNames() {
                //                            (Account)
        // sendDate, AccountID, OrderID, FirstName, LastName, items list as string
        String[] columnNames = {
            "First Name",
            "Last Name",
            "Start Time",
            "End Time"
        };
        return columnNames;
    }
    

    private Object[][] getData() {

        //                            (Account)
        // sendDate, AccountID, OrderID, FirstName, LastName, items list as string
        Object[][] dataArr = new Object[][]{
            {"John", "Doe", "Sun Nov 27 09:00:00 EST 2022", "Sun Nov 27 17:00:00 EST 2022"},
            {"Jane", "Doe", "Sun Nov 27 09:00:00 EST 2022", "Sun Nov 27 12:00:00 EST 2022"},
            {"Aaron", "Collins", "Sun Nov 27 02:00:00 EST 2022", "Sun Nov 27 22:00:00 EST 2022"} 
        };

        

        return dataArr;
    }
   
    private void sortTableRows() {
        jTable1.setAutoCreateRowSorter(true);
        List<RowSorter.SortKey> sortKeys = new ArrayList<>(1);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
        jTable1.getRowSorter().setSortKeys(sortKeys);
    }
    
    /**
     * Creates new form WeeklyOrdersPanelV2
     */
    public ViewDaySchedule(MainDisplay display) {
        this.display = display;
        initComponents();
        sortTableRows();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        setBackground(new java.awt.Color(33, 33, 33));
        setForeground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(850, 500));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(33, 33, 33));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 410));
        jScrollPane1.setRowHeaderView(null);
        jScrollPane1.setViewportView(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(getData(), getColumnNames()));
        jTable1.setSelectionBackground(new java.awt.Color(71, 1, 194));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private JButton[] buttons;
    private WeeklyOrder[] data;
    private MainDisplay display;

    
}
