/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.NewGUI.Panels.AddOrder.AddItem.BookPanel;

/**
 *
 * @author aaron
 */
public class BookPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewBookPanel
     */
    public BookPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookNamePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BookNameField = new javax.swing.JTextField();
        PricePanel = new javax.swing.JPanel();
        PriceNameField = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PriceField = new javax.swing.JTextField();
        AuthorPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AuthorField = new javax.swing.JTextField();
        ISBNPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ISBNField = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 120), new java.awt.Dimension(0, 120), new java.awt.Dimension(32767, 120));

        setBackground(new java.awt.Color(33, 33, 33));
        setMinimumSize(new java.awt.Dimension(850, 270));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(850, 270));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        BookNamePanel.setBackground(new java.awt.Color(33, 33, 33));
        BookNamePanel.setPreferredSize(new java.awt.Dimension(750, 40));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5);
        flowLayout1.setAlignOnBaseline(true);
        BookNamePanel.setLayout(flowLayout1);

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));
        jPanel2.setPreferredSize(new java.awt.Dimension(340, 100));
        java.awt.FlowLayout flowLayout5 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout5.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout5);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Name:");
        jPanel2.add(jLabel1);

        BookNameField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BookNameField.setToolTipText("Enter Book Name");
        BookNameField.setMinimumSize(new java.awt.Dimension(200, 28));
        BookNameField.setPreferredSize(new java.awt.Dimension(200, 28));
        BookNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(BookNameField);

        BookNamePanel.add(jPanel2);

        add(BookNamePanel);

        PricePanel.setBackground(new java.awt.Color(33, 33, 33));
        PricePanel.setPreferredSize(new java.awt.Dimension(750, 40));
        java.awt.FlowLayout flowLayout7 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5);
        flowLayout7.setAlignOnBaseline(true);
        PricePanel.setLayout(flowLayout7);

        PriceNameField.setBackground(new java.awt.Color(33, 33, 33));
        PriceNameField.setPreferredSize(new java.awt.Dimension(340, 100));
        java.awt.FlowLayout flowLayout6 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout6.setAlignOnBaseline(true);
        PriceNameField.setLayout(flowLayout6);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Price:");
        PriceNameField.add(jLabel2);

        PriceField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PriceField.setToolTipText("Enter Book Name");
        PriceField.setMinimumSize(new java.awt.Dimension(200, 28));
        PriceField.setPreferredSize(new java.awt.Dimension(200, 28));
        PriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceFieldActionPerformed(evt);
            }
        });
        PriceNameField.add(PriceField);

        PricePanel.add(PriceNameField);

        add(PricePanel);

        AuthorPanel.setBackground(new java.awt.Color(33, 33, 33));
        AuthorPanel.setPreferredSize(new java.awt.Dimension(750, 40));
        java.awt.FlowLayout flowLayout9 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5);
        flowLayout9.setAlignOnBaseline(true);
        AuthorPanel.setLayout(flowLayout9);

        jPanel6.setBackground(new java.awt.Color(33, 33, 33));
        jPanel6.setPreferredSize(new java.awt.Dimension(340, 100));
        java.awt.FlowLayout flowLayout8 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout8.setAlignOnBaseline(true);
        jPanel6.setLayout(flowLayout8);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Author:");
        jPanel6.add(jLabel3);

        AuthorField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AuthorField.setToolTipText("Enter Book Name");
        AuthorField.setMinimumSize(new java.awt.Dimension(200, 28));
        AuthorField.setPreferredSize(new java.awt.Dimension(200, 28));
        AuthorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorFieldActionPerformed(evt);
            }
        });
        jPanel6.add(AuthorField);

        AuthorPanel.add(jPanel6);

        add(AuthorPanel);

        ISBNPanel.setBackground(new java.awt.Color(33, 33, 33));
        ISBNPanel.setPreferredSize(new java.awt.Dimension(750, 40));
        java.awt.FlowLayout flowLayout11 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5);
        flowLayout11.setAlignOnBaseline(true);
        ISBNPanel.setLayout(flowLayout11);

        jPanel8.setBackground(new java.awt.Color(33, 33, 33));
        jPanel8.setPreferredSize(new java.awt.Dimension(340, 100));
        java.awt.FlowLayout flowLayout10 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout10.setAlignOnBaseline(true);
        jPanel8.setLayout(flowLayout10);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ISBN:");
        jPanel8.add(jLabel4);

        ISBNField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ISBNField.setToolTipText("Enter Book Name");
        ISBNField.setMinimumSize(new java.awt.Dimension(200, 28));
        ISBNField.setPreferredSize(new java.awt.Dimension(200, 28));
        ISBNField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNFieldActionPerformed(evt);
            }
        });
        jPanel8.add(ISBNField);

        ISBNPanel.add(jPanel8);

        add(ISBNPanel);
        add(filler1);
    }// </editor-fold>//GEN-END:initComponents

    private void BookNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookNameFieldActionPerformed

    private void ISBNFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNFieldActionPerformed

    private void AuthorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorFieldActionPerformed

    private void PriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AuthorField;
    private javax.swing.JPanel AuthorPanel;
    public javax.swing.JTextField BookNameField;
    private javax.swing.JPanel BookNamePanel;
    public javax.swing.JTextField ISBNField;
    private javax.swing.JPanel ISBNPanel;
    public javax.swing.JTextField PriceField;
    private javax.swing.JPanel PriceNameField;
    private javax.swing.JPanel PricePanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
