/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookstore.NewGUI.Panels.CreateAccount;

import com.bookstore.NewGUI.Panels.AddOrder.AddItem.*;
import com.bookstore.Models.ItemType;
import com.bookstore.NewGUI.ButtonHelper.ButtonHelper;
import com.bookstore.NewGUI.ComboBoxHelper.ComboBoxRenderer;
import com.bookstore.NewGUI.MainDisplay;
import com.bookstore.NewGUI.Panels.AddOrder.AddItem.BookPanel.BookPanel;
import com.bookstore.NewGUI.Panels.AddOrder.AddItem.ClothingPanel.ClothingPanel;
import com.bookstore.NewGUI.Panels.AddOrder.AddItem.OtherPanel.OtherPanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;

/**
 *
 * @author aaron
 */
public class CreateAccount extends javax.swing.JPanel {
        
    JPanel dynamicPanel;
    
    public void setScrollPanel(JPanel panel) {
        this.dynamicPanel = panel;
        jPanel5.removeAll();
        jPanel5.add(this.dynamicPanel);
        this.revalidate();
        this.repaint();
    }

    
    private String[] getTypes() {
        ItemType[] itemTypes = ItemType.values();
        String[] itemTypeStrArr = new String[itemTypes.length];
        for(int i = 0; i < itemTypes.length; i++) {
            itemTypeStrArr[i] = itemTypes[i].toString();
        }
        return itemTypeStrArr;
    }
    
    /**
     * Creates new form AddItem
     */
    public CreateAccount(MainDisplay display) {
        this.display = display;
        initComponents();
        this.buttons = new JButton[] {jButton1};
        ButtonHelper.addButtonHighlights(buttons);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        FirstNamePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        LastNamePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(33, 33, 33));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(850, 66));
        setPreferredSize(new java.awt.Dimension(850, 500));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(33, 33, 33));
        jPanel3.setMinimumSize(new java.awt.Dimension(850, 140));
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 140));

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setMinimumSize(new java.awt.Dimension(838, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(838, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Account");
        jLabel1.setMaximumSize(new java.awt.Dimension(220, 48));
        jLabel1.setMinimumSize(new java.awt.Dimension(220, 48));
        jLabel1.setPreferredSize(new java.awt.Dimension(220, 48));
        jPanel1.add(jLabel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(33, 33, 33));
        jPanel4.setMinimumSize(new java.awt.Dimension(850, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(850, 50));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jButton1.setText("Create Account");
        jButton1.setMaximumSize(new java.awt.Dimension(150, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(150, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel5.setBackground(new java.awt.Color(33, 33, 33));

        FirstNamePanel.setBackground(new java.awt.Color(33, 33, 33));
        FirstNamePanel.setMinimumSize(new java.awt.Dimension(850, 50));
        FirstNamePanel.setPreferredSize(new java.awt.Dimension(850, 50));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5);
        flowLayout2.setAlignOnBaseline(true);
        FirstNamePanel.setLayout(flowLayout2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name:");
        FirstNamePanel.add(jLabel3);

        jTextField1.setToolTipText("");
        jTextField1.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        FirstNamePanel.add(jTextField1);

        jPanel5.add(FirstNamePanel);

        LastNamePanel.setBackground(new java.awt.Color(33, 33, 33));
        LastNamePanel.setMinimumSize(new java.awt.Dimension(850, 50));
        LastNamePanel.setPreferredSize(new java.awt.Dimension(850, 50));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5);
        flowLayout3.setAlignOnBaseline(true);
        LastNamePanel.setLayout(flowLayout3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name: ");
        LastNamePanel.add(jLabel4);

        jTextField2.setToolTipText("");
        jTextField2.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField2.setPreferredSize(new java.awt.Dimension(200, 30));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        LastNamePanel.add(jTextField2);

        jPanel5.add(LastNamePanel);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.display.setNewPanel(new CreateAccount(this.display));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FirstNamePanel;
    private javax.swing.JPanel LastNamePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private JButton[] buttons;
    private MainDisplay display;

}
